  name: CI pipeline

  # trigger on ghosty-test branch
  on:
    push:
      branches:
        - ghosty_test
    pull_request:
      branches:
        - ghosty_test

  jobs:
    unit-tests:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        # set up Go envir
        - name: Set up Go
          uses: actions/setup-go@v5
          with:
            go-version: '1.21'

        - name: Install dependencies
          run: go mod download

        # run unit tests with coverage
        - name: Run Unit Tests
          run: go test ./services/user/tests/unit/... -v -cover -coverprofile=coverage.out

    lint:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Go
          uses: actions/setup-go@v5
          with:
            go-version: '1.21'

        - name: Install golangci-lint
          run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.61.0

        - name: Run golangci-lint
          run: golangci-lint run ./...

    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Go
          uses: actions/setup-go@v5
          with:
            go-version: '1.21'

        - name: Build
          run: go build ./...
